version: "3.9"
services:
  mongo:
    image: mongo:7
    container_name: iot_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: iot_backend
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://mongo:27017/iot
      - JWT_SECRET=supersecretchangeme
      - PORT=4000
      - CORS_ORIGIN=http://localhost:5173
    depends_on:
      - mongo
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    container_name: iot_frontend
    restart: unless-stopped
    environment:
      - VITE_API_BASE=http://localhost:4000
    depends_on:
      - backend
    ports:
      - "5173:5173"

  simulator:
    image: node:20-alpine
    container_name: iot_simulator
    working_dir: /app
    depends_on:
      - backend
    volumes:
      - ./backend/scripts:/app
    command: ["node", "simulate.js"]
    environment:
      - API_BASE=http://backend:4000
    restart: unless-stopped

volumes:
  mongo_data:
